# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ledger.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ledger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cledger.proto\x12\tledger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nowner_name\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x04 \x01(\x03\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"$\n\x0e\x41\x63\x63ountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"?\n\x07\x42\x61lance\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\"\xc9\x01\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\x12\x17\n\x0f\x66rom_account_id\x18\x03 \x01(\t\x12\x15\n\rto_account_id\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x03\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x15\n\rreview_status\x18\x07 \x01(\t\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"E\n\x10TransactionQuery\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"N\n\x0fTransactionList\x12,\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x16.ledger.v1.Transaction\x12\r\n\x05total\x18\x02 \x01(\x05\"L\n\x0b\x46lagRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x15\n\rreview_status\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\"N\n\x0c\x46lagResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x15\n\rreview_status\x18\x03 \x01(\t2\xe3\x01\n\rLedgerService\x12J\n\x0fGetTransactions\x12\x1b.ledger.v1.TransactionQuery\x1a\x1a.ledger.v1.TransactionList\x12\x42\n\x11GetAccountBalance\x12\x19.ledger.v1.AccountRequest\x1a\x12.ledger.v1.Balance\x12\x42\n\x0f\x46lagTransaction\x12\x16.ledger.v1.FlagRequest\x1a\x17.ledger.v1.FlagResponseB-Z+github.com/muhammadali/ledger-go/grpc/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ledger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/muhammadali/ledger-go/grpc/pb;pb'
  _globals['_ACCOUNT']._serialized_start=60
  _globals['_ACCOUNT']._serialized_end=184
  _globals['_ACCOUNTREQUEST']._serialized_start=186
  _globals['_ACCOUNTREQUEST']._serialized_end=222
  _globals['_BALANCE']._serialized_start=224
  _globals['_BALANCE']._serialized_end=287
  _globals['_TRANSACTION']._serialized_start=290
  _globals['_TRANSACTION']._serialized_end=491
  _globals['_TRANSACTIONQUERY']._serialized_start=493
  _globals['_TRANSACTIONQUERY']._serialized_end=562
  _globals['_TRANSACTIONLIST']._serialized_start=564
  _globals['_TRANSACTIONLIST']._serialized_end=642
  _globals['_FLAGREQUEST']._serialized_start=644
  _globals['_FLAGREQUEST']._serialized_end=720
  _globals['_FLAGRESPONSE']._serialized_start=722
  _globals['_FLAGRESPONSE']._serialized_end=800
  _globals['_LEDGERSERVICE']._serialized_start=803
  _globals['_LEDGERSERVICE']._serialized_end=1030
# @@protoc_insertion_point(module_scope)
