# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ledger_pb2 as ledger__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ledger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LedgerServiceStub(object):
    """─── Service ──────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTransactions = channel.unary_unary(
                '/ledger.v1.LedgerService/GetTransactions',
                request_serializer=ledger__pb2.TransactionQuery.SerializeToString,
                response_deserializer=ledger__pb2.TransactionList.FromString,
                _registered_method=True)
        self.GetAccountBalance = channel.unary_unary(
                '/ledger.v1.LedgerService/GetAccountBalance',
                request_serializer=ledger__pb2.AccountRequest.SerializeToString,
                response_deserializer=ledger__pb2.Balance.FromString,
                _registered_method=True)
        self.FlagTransaction = channel.unary_unary(
                '/ledger.v1.LedgerService/FlagTransaction',
                request_serializer=ledger__pb2.FlagRequest.SerializeToString,
                response_deserializer=ledger__pb2.FlagResponse.FromString,
                _registered_method=True)


class LedgerServiceServicer(object):
    """─── Service ──────────────────────────────────────────────────────
    """

    def GetTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlagTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LedgerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactions,
                    request_deserializer=ledger__pb2.TransactionQuery.FromString,
                    response_serializer=ledger__pb2.TransactionList.SerializeToString,
            ),
            'GetAccountBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountBalance,
                    request_deserializer=ledger__pb2.AccountRequest.FromString,
                    response_serializer=ledger__pb2.Balance.SerializeToString,
            ),
            'FlagTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.FlagTransaction,
                    request_deserializer=ledger__pb2.FlagRequest.FromString,
                    response_serializer=ledger__pb2.FlagResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ledger.v1.LedgerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ledger.v1.LedgerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LedgerService(object):
    """─── Service ──────────────────────────────────────────────────────
    """

    @staticmethod
    def GetTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.v1.LedgerService/GetTransactions',
            ledger__pb2.TransactionQuery.SerializeToString,
            ledger__pb2.TransactionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.v1.LedgerService/GetAccountBalance',
            ledger__pb2.AccountRequest.SerializeToString,
            ledger__pb2.Balance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlagTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.v1.LedgerService/FlagTransaction',
            ledger__pb2.FlagRequest.SerializeToString,
            ledger__pb2.FlagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
